CC=g++
CFLAGS=-std=c++11 -DLOGLEVEL=WARNING -pthread
LDFLAGS=
SOURCE_PATH=src
BIN_PATH=bin
DEPENDENCIES=src/**/*.cpp
SOURCE=src/Interpreter.cpp
EXECUTABLE=$(BIN_PATH)/tiny
SYSTEM_PATH=/usr/local/bin
EXAMPLE_FILE=examples/full.tl
FORMAT_EXECUTABLE=bin/format

all: $(EXECUTABLE)
$(EXECUTABLE):
	$(CC) $(CFLAGS) $(DEPENDENCIES) $(SOURCE) -o $(EXECUTABLE)

run:
	$(EXECUTABLE) $(EXAMPLE_FILE)

format:
	$(FORMAT_EXECUTABLE)

install:
	cp $(EXECUTABLE) $(SYSTEM_PATH)

clean:
	rm $(EXECUTABLE)
