numero resultado = (5+2)
              *5;

imprimir resultado;

numero resultado = resultado + 3;

imprimir resultado;

texto nome = "victor g  antoniazz
 i";

imprimir nome;

texto idade = "20";
numero idade = idade + 10;
imprimir idade;

caso(resultado == resultado)
  imprimir resultado;
fim

assincrono numero x = 10;
assincrono imprimir x;

imprimir "Dê um valor pra x:";

lerLinha associar numero x;
imprimir x;
